from typing import Self

class Car:
    LIMITER:int = 220
    
    def __init__(self,brand:str, max_speed:int) -> None:
        self.brand = brand
        self.max_speed = max_speed
        
    @classmethod #refers to the class itself , not the instance of the class
    def change_limit(cls, new_limit:int) -> None: #cls keyword is needed otherwise python will think we referingf to the instance
       cls.LIMITER = new_limit 
       
    @classmethod
    def autogenerated_max_speed(cls, brand:str) -> Self:
        lowered: str = brand.lower()  
        max_speed: int = 200
        
        if lowered == 'golf':
           max_speed = 300
        elif lowered == 'Volvo':
            max_speed = 320
            
        return cls(brand, max_speed)    
       
       
    def display_info(self) -> None:
        print(f'{self.brand} (max= {self.max_speed}, limit={self.LIMITER})')   
        
def main():
    print(" ")
    vw :Car = Car('Golf', 200)
    volvo :Car = Car('Volvo', 260)
    
    #display the info of the cars before changing speed limit
    vw.display_info() 
    volvo.display_info()
    print(" ")
    #we'll change the class attribute LIMITER , 
    # this means that the limit for all instance of the class will be affected
    Car.change_limit(440) #cahnge_limit is a class method so it affects all the instances 
    vw.display_info()
    volvo.display_info()
    print(" ")
    
    BMW : Car = Car.autogenerated_max_speed('BMW')
    BMW.display_info()
    print(" ")
    
    
    
    
if __name__ == "__main__":
    main()
 